[package]
name = "dtui"
version = "0.1.0"
authors = ["The0x539 <the0x539@gmail.com>"]
edition = "2018"

[dependencies]
serde = "*"
tokio = "*"
cursive = { version = "*", default-features = false, features = ["crossterm-backend"] }
deluge-rpc = "0.3.0"
deluge-rpc-macro = "0.3.0"
serde_yaml = "*"
human_format = "*"
cursive-tabs = "*"

[patch.crates-io]
webpki = { path = "./experiment/webpki" }
