[package]
name = "dtui"
version = "0.1.0"
authors = ["The0x539 <the0x539@gmail.com>"]
edition = "2018"

[dependencies]
serde = "*"
tokio = "*"
cursive = { version = "0.14.1", default-features = false, features = ["crossterm-backend"] }
deluge-rpc = "0.5.3"
serde_yaml = "*"
human_format = "*"
cursive-tabs = "*"
cursive_buffered_backend = "0.3.3"
futures = "*"

[patch.crates-io]
webpki = { path = "./experiment/webpki" }
