[package]
name = "dtui"
version = "0.1.0"
authors = ["The0x539 <the0x539@gmail.com>"]
edition = "2018"

[dependencies]
serde = "*"
tokio = "*"
cursive = { version = "0.14.1", default-features = false, features = ["crossterm-backend"] }
deluge-rpc.path = "../deluge-rpc"
bytesize = "1.0.1"
cursive-tabs = "*"
cursive_buffered_backend = "0.3.3"
futures = "*"
fnv = "1.0.7"
ryu = "1.0.4"
async-trait = "0.1.31"

[patch.crates-io]
deluge-rpc-macro = { path = "../deluge-rpc/experiment/deluge-rpc-macro" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
